test-defaults: &test-defaults
  docker:
    - image: quay.io/pantheon-public/terminus-plugin-test:1.x
  working_directory: ~/work/wp
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

version: 2
jobs:
    test:
        <<: *test-defaults
        steps:
            - checkout
            - run:
                name: Set up environment
                command: sleep 300

workflows:
  version: 2
  wordpress:
    jobs:
      - test